### ISSUE TITLE
Missing memory management attributes on properties

### ISSUE THREAD

**Issue by dbquarrel** [microsoft/appcenter-sdk-apple#1711]
### **Description**

Xcode 11 beta 5 is starting to warn about this issue which is indeed a problem: almost all of the properties that make objects available are assign properties. They need to specify one of weak, assign, strong, or retain. They are relying on default behavior which is assign. If you really want assign it should be stated but it is probably not correct behavior.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install via cocopods
2. Compile with Xcode 11 beta 5  (in my case ARC is not enabled for my project, but I haven't specified anything specifically for the appcenter pod...)
3. you will be greeted with dozens of these warnings:

    No 'assign', 'retain' or 'copy' attribute is specified - 'assign' is assumed.
    Default property attribute 'assign' not appropriate for object
    While building module 'AppCenter'  imported from ...

Affected properties are declared like this:

    @property(nonatomic) NSDate *timestamp;

And they should probably either be strong, or retain specified (I think).

I'm not sure if you're assuming ARC is in use by developers (can't assume or force them to use ARC). It seems to be using its own framework so it should be OK to use ARC internally but the properties need to be declared correctly.

I'm not sure about the framework settings and not a podfile expert here. Just that one way or another assignments are probably wrong for most of these cases.

If assign is intended behavior it should be probably accompanied by (readonly) for the user exposed API. You shouldn't be accepting users sending in assign objects other than for delegate situations where you want to avoid reference loops.

### **Details**

1. Which SDK version are you using?
    2.2.0

2. Which OS version did you experience the issue on?
    iOS 13 beta 5

3. Which Cocoapods version are you using (run `pod --version`)?
    1.7.5

4. What device version did you see this error on?  Were you using an emulator or a physical device?
    iPhone XR physical device running iOS 13 beta 5

5. What language are you using?
    Using the Objective C AppCenter kit but my app has both ObjC and Swift in it, primarily ObjC.

6. What third party libraries are you using?
    iOS Charts 3.3.0

7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

    It's not a runtime error, it's a compile time error.

**Comment by guperrot** [comment]
Hi, thanks for the report.
Some of it has been fixed in #1706 and we have an internal bug filed to fix the remaining properties.

**Comment by annakocheshkova** [comment]
Hi there! This has been fixed, please check out the latest SDK version and let us know if anything's wrong.

**Comment by dbquarrel** [comment]
This problem is back again with some of the newer properties.

From MSACAppCenter.h:

    @property(class, nonatomic) NSString *logUrl;
    @property(class, nonatomic) MSACWrapperSdk *wrapperSdk;
    @property(class, nonatomic) NSString *userId;
    @property(class, nonatomic) NSString *countryCode;

As above, needs one of "copy", "assign", "retain", "weak" or "strong".

**Comment by MatkovIvan** [comment]
Fixed in [4.1.1](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.1.1)
